"use client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import SplashScreen from "@/components/SplashScreen/SplashScreen";
import { AuthContextProvider } from "@/context/AuthContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const dmSans = DM_Sans({
  subsets: ["latin"], // Specify which subsets you want to load  // You can specify the font weight if you want
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showSplash, setShowSplash] = useState(false);
  // useEffect(() => {
  //   const splashTimeout = setTimeout(() => {
  //     setShowSplash(false);
  //   }, 3500);
  //   return () => clearTimeout(splashTimeout);
  // }, []);
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
        {showSplash ? (
          <SplashScreen key="splash" />
        ) : (
          <body
            className={`${dmSans.className} flex justify-center min-h-screen relative`}
          >
            <div className="w-full max-w-[1900px] relative p-12 overflow-hidden mt-12">
              <AuthContextProvider>
                <Header />
                {children}
                <Footer />
              </AuthContextProvider>
            </div>
          </body>
        )}
      </AnimatePresence>
    </html>
  );
}
